"""empty message

Revision ID: 5b1507ef956a
Revises: 
Create Date: 2017-07-18 11:55:36.145927

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5b1507ef956a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('debates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('views', sa.Integer(), nullable=True),
    sa.Column('dtype', sa.String(length=40), nullable=True),
    sa.Column('topic', sa.String(length=100), nullable=True),
    sa.Column('current_round_number', sa.Integer(), nullable=True),
    sa.Column('stage', sa.String(length=10), nullable=True),
    sa.Column('max_round_number', sa.Integer(), nullable=True),
    sa.Column('max_claim_number', sa.Integer(), nullable=True),
    sa.Column('isTimed', sa.String(length=10), nullable=True),
    sa.Column('time_for_next_phase', sa.DateTime(), nullable=True),
    sa.Column('pro_votes', sa.Integer(), nullable=True),
    sa.Column('con_votes', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=40), nullable=False),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('avatar', sa.Text(), nullable=True),
    sa.Column('isVIP', sa.Boolean(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('tokens', sa.Text(), nullable=True),
    sa.Column('wins', sa.Integer(), nullable=True),
    sa.Column('losses', sa.Integer(), nullable=True),
    sa.Column('send_user_joined_emails', sa.Boolean(), nullable=True),
    sa.Column('send_round_continue_emails', sa.Boolean(), nullable=True),
    sa.Column('send_voting_notification_emails', sa.Boolean(), nullable=True),
    sa.Column('send_debate_finished_emails', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('claims',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('debate_id', sa.Integer(), nullable=True),
    sa.Column('opposing_claim_id', sa.Integer(), nullable=True),
    sa.Column('enthymeme_claim', sa.String(length=1500), nullable=True),
    sa.Column('enthymeme_justification', sa.String(length=1500), nullable=True),
    sa.Column('round_number', sa.Integer(), nullable=True),
    sa.Column('user_type', sa.String(length=10), nullable=True),
    sa.ForeignKeyConstraint(['debate_id'], ['debates.id'], ),
    sa.ForeignKeyConstraint(['opposing_claim_id'], ['claims.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('definitions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('debate_id', sa.Integer(), nullable=True),
    sa.Column('term', sa.String(length=25), nullable=True),
    sa.Column('body', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['debate_id'], ['debates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_debate',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('debate_id', sa.Integer(), nullable=False),
    sa.Column('user_type', sa.String(length=10), nullable=True),
    sa.ForeignKeyConstraint(['debate_id'], ['debates.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'debate_id')
    )
    op.create_table('user_vote_tally',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('debate_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['debate_id'], ['debates.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_vote_tally')
    op.drop_table('user_debate')
    op.drop_table('definitions')
    op.drop_table('claims')
    op.drop_table('users')
    op.drop_table('debates')
    # ### end Alembic commands ###
