"""empty message

Revision ID: c3eba9b8b87c
Revises: 5b1507ef956a
Create Date: 2017-08-07 14:02:56.308280

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c3eba9b8b87c'
down_revision = '5b1507ef956a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('debates', sa.Column('has_sent_finished_emails', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('debates', 'has_sent_finished_emails')
    # ### end Alembic commands ###
